apiVersion: apps/v1
kind: Deployment
metadata:
  name: snakeweb-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: cbenseler/snakeweb:20210209
        imagePullPolicy: Always
        ports:
        - containerPort: 80